### ISSUE TITLE
Remove the Tag

### ISSUE THREAD

**Issue by Nostrabramus** [Nostrabramus/CookieLawManagement#3]
@instruccionesaldorso wrote:
I wanted to ask something else: as far as I see, there is no possibility to remove the "Tag" shown on the left part (vertical) by default, only the possibility to put it in a different position. Could this be a new feature?
The only way I could remove it is replacing the JavaScript directly.

**Comment by Nostrabramus** [comment]
@instruccionesaldorso we have already introduced this option since version 8.7.2.
You can remove it using costant editor or writing in your typoscript the constant

`  plugin.tx_aipcookielaw.settings.OnOffPopUp = 0` 

you can still keep the popup functionality adding the attribute 

` onclick = "$ ('body'). prepend (cc.showmodal) ` 

into a button or a link to show the privacy pop-up

**Comment by instruccionesaldorso** [comment]
@Nostrabramus This option removes the WHOLE cookie consent (the one by default on bottom of the page, and the tag on the left).
I tried this with latest version 8.7.5 and an incognito window.
Can you try it, please?

**Comment by Nostrabramus** [comment]
@instruccionesaldorso you're right, we just fixed the problem. 
You can download the new version from GitHub and configure it as I wrote in the first answer, or you can wait for the publication on TER that will happen soon.
Thanks for the tip

**Comment by instruccionesaldorso** [comment]
Fixed in the new version! Thanks!
