### ISSUE TITLE
All texts are shown as "undefined" - missing template

### ISSUE THREAD

**Issue by jcdirks** [Nostrabramus/CookieLawManagement#6]
With the latest change in `ConvertXmlToJsonController.php`, the JSON rquest to get the translated strings fails. Reverting back to `return json_encode($message, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);` in line 36 fixes the issue. Is there a template missing from the latest commit?

**Comment by GuidoJansen** [comment]
The error message in the AJAX call is as follows

```
<p><strong>Sorry, the requested view was not found.</strong></p>
<p>The technical reason is: <em>No template was found. View could not be resolved for action "getJson" in class "Aip\AipCookieLaw\Controller\ConvertXmlToJsonController"</em>.</p>
```

It seems that there is a Template missing in Resources/Private/Templates/

**Comment by GuidoJansen** [comment]
I think this change should not be part of the commit.

What is missing is the setting of member $defaultViewObjectName from this pull request by Sergio Catalá:
https://github.com/Nostrabramus/CookieLawManagement/pull/4/commits/03a04db49332835883177ea06ce2080719373d58

**Comment by Nostrabramus** [comment]
@jcdirks @GuidoJansen thanks for the report and tips,
we'll take a look at it as soon as possible

**Comment by Nostrabramus** [comment]
Fixed, 
thanks again
