### ISSUE TITLE
External Resources  / third party requests

### ISSUE THREAD

**Issue by nom10s** [Nostrabramus/CookieLawManagement#8]
Thank you for this valuable extension. I have a suggestion for improvement: The extension loads external resources from Google Fonts, Amazon and silktide.com. This is questionable with regard to GDPR.

In addition some external resources lead to an error 404.

The CSS file CookieLaw.css loads these files (with error 404):
https://s3-eu-west-1.amazonaws.com/assets.cookieconsent.silktide.com/cross.png
https://s3-eu-west-1.amazonaws.com/assets.cookieconsent.silktide.com/silktide-logo.png
https://s3-eu-west-1.amazonaws.com/assets.cookieconsent.silktide.com/cookie-consent-logo.png
http://assets.cookieconsent.silktide.com/cookie-consent-box.png
https://s3-eu-west-1.amazonaws.com/assets.cookieconsent.silktide.com/globe.png

From line 1488 of the Javascript file CookieLaw.js a Google font is included.
This practical tool makes it easy to integrate Google Fonts locally: https://google-webfonts-helper.herokuapp.com/fonts/open-sans?subsets=latin

I am sure that the extension would be even more valuable without the use of external resources! If you don't mind, I'd be happy to donate source code.

**Comment by Nostrabramus** [comment]
thanks for your feedback, 
we will fix this problems as soon as possible

**Comment by Nostrabramus** [comment]
@nom10s it's done
thanks again for the report
